name: Hugo Actions # 名字自取

on:
  push:
    branches:
      - main  # 当 main 分支发生 push 的时候，运行下面的 jobs

jobs:
  deploy: 
    runs-on: ubuntu-latest # 在什么环境运行任务
    steps:
      - uses: actions/checkout@v4   # 引用 actions/checkout 这个 action，与所在的 github 仓库同名
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 获取 submodule 主题
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Setup Hugo # 步骤名自取
        uses: peaceiris/actions-hugo@v2   # Hugo 官方提供的 action，用于在任务环境中获取 hugo
        with:
          hugo-version: '0.122.0' # 获取指定版本的 hugo
          extended: false

      - name: Build Site
        run: |
          # 1. 自动获取你当前仓库的实际文件夹名称
          CURRENT_DIR=$(basename $(pwd))
          # 2. 去到上级目录，建一个叫 WebStack-Hugo 的软链接指向它，完美满足 Hugo 的要求
          cd .. && ln -s "$CURRENT_DIR" WebStack-Hugo && cd "$CURRENT_DIR"
          # 3. 复制示例文件
          cp -R exampleSite/* .
          # 4. 执行编译，并将 baseURL 改为你自己的 GitHub Pages 地址
          hugo --themesDir ../ --baseURL https://adolfshhz1.github.io/chizf-WebStack-Hugo/
          
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3   # 一个自动发布 github pages 的 action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自动生成的免密 Token，无需手动填 API
          publish_dir: ./public 
          publish_branch: gh-pages # 发布到当前仓库的 gh-pages 分支
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
